# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowaviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.labelimg = QtWidgets.QLabel(Dialog)
        self.labelimg.setGeometry(QtCore.QRect(160, 40, 81, 71))
        self.labelimg.setText("")
        self.labelimg.setPixmap(QtGui.QPixmap("img/warning.png"))
        self.labelimg.setScaledContents(True)
        self.labelimg.setObjectName("labelimg")
        self.labelSalir = QtWidgets.QLabel(Dialog)
        self.labelSalir.setGeometry(QtCore.QRect(160, 120, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelSalir.setFont(font)
        self.labelSalir.setObjectName("labelSalir")
        self.btnBox = QtWidgets.QDialogButtonBox(Dialog)
        self.btnBox.setGeometry(QtCore.QRect(130, 180, 156, 23))
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnBox.setObjectName("btnBox")
        self.btnBox.accepted.connect(Dialog.accept)
        self.btnBox.rejected.connect(Dialog.reject)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelSalir.setText(_translate("Dialog", "Desea salir?"))
