# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venMayor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogMayor(object):
    def setupUi(self, DialogMayor):
        DialogMayor.setObjectName("DialogMayor")
        DialogMayor.resize(400, 300)
        self.labelimg = QtWidgets.QLabel(DialogMayor)
        self.labelimg.setGeometry(QtCore.QRect(160, 40, 81, 71))
        self.labelimg.setText("")
        self.labelimg.setPixmap(QtGui.QPixmap("img/warning.png"))
        self.labelimg.setScaledContents(True)
        self.labelimg.setObjectName("labelimg")
        self.labelSalir = QtWidgets.QLabel(DialogMayor)
        self.labelSalir.setGeometry(QtCore.QRect(60, 120, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelSalir.setFont(font)
        self.labelSalir.setObjectName("labelSalir")
        self.btnSalir = QtWidgets.QPushButton(DialogMayor)
        self.btnSalir.setGeometry(QtCore.QRect(170, 160, 75, 23))
        self.btnSalir.setObjectName("btnSalir")

        self.retranslateUi(DialogMayor)
        QtCore.QMetaObject.connectSlotsByName(DialogMayor)

    def retranslateUi(self, DialogMayor):
        _translate = QtCore.QCoreApplication.translate
        DialogMayor.setWindowTitle(_translate("DialogMayor", "Dialog"))
        self.labelSalir.setText(_translate("DialogMayor", "Para continuar debes ser mayor de edad"))
        self.btnSalir.setText(_translate("DialogMayor", "Salir"))
